<?php

//所有mime和扩展名对应
function mime(){
    return array (
        'application/internet-property-stream' => 'acx',
        'application/postscript' => 'ai eps ps',
        'audio/x-aiff' => 'aif aifc aiff',
        'video/x-ms-asf' => 'asf asr asx lsf lsx',
        'audio/basic' => 'au snd',
        'video/x-msvideo' => 'avi',
        'application/olescript' => 'axs',
        'text/plain' => 'bas c h txt asc',
        'application/x-bcpio' => 'bcpio',
        'application/octet-stream' => 'bin class dms exe lha lzh ani avb bpk cur dll dmg ico tad ttf',
        'image/bmp' => 'bmp',
        'application/vnd.ms-pkiseccat' => 'cat',
        'application/x-cdf' => 'cdf',
        'application/x-x509-ca-cert' => 'cer crt der',
        'application/x-msclip' => 'clp',
        'image/x-cmx' => 'cmx',
        'image/cis-cod' => 'cod',
        'application/x-cpio' => 'cpio',
        'application/x-mscardfile' => 'crd',
        'application/pkix-crl' => 'crl',
        'application/x-csh' => 'csh',
        'text/css' => 'css',
        'application/x-director' => 'dcr dir dxr',
        'application/x-msdownload' => 'dll',
        'application/msword' => 'doc dot',
        'application/x-dvi' => 'dvi',
        'text/x-setext' => 'etx',
        'application/envoy' => 'evy',
        'application/fractals' => 'fif',
        'x-world/x-vrml' => 'flr vrml wrl wrz xaf xof',
        'image/gif' => 'gif ifm',
        'application/x-gtar' => 'gtar',
        'application/x-gzip' => 'gz x-gzip',
        'application/x-hdf' => 'hdf',
        'application/winhlp' => 'hlp',
        'application/mac-binhex40' => 'hqx',
        'application/hta' => 'hta',
        'text/x-component' => 'htc',
        'text/html' => 'htm html stm dhtml hts',
        'text/webviewhtml' => 'htt',
        'image/x-icon' => 'ico',
        'image/ief' => 'ief',
        'application/x-iphone' => 'iii',
        'application/x-internet-signup' => 'ins isp',
        'image/pipeg' => 'jfif',
        'image/jpeg' => 'jpe jpeg jpg jpz',
        'image/pjpeg' => 'jpg',
        'application/x-javascript' => 'js',
        'application/x-latex' => 'latex',
        'video/x-la-asf' => 'lsf lsx',
        'application/x-msmediaview' => 'm13 m14 mvb',
        'audio/x-mpegurl' => 'm3u m3url',
        'application/x-troff-man' => 'man',
        'application/x-msaccess' => 'mdb',
        'application/x-troff-me' => 'me',
        'message/rfc822' => 'mht mhtml nws',
        'audio/mid' => 'mid rmi',
        'application/x-msmoney' => 'mny',
        'video/quicktime' => 'mov qt',
        'video/x-sgi-movie' => 'movie',
        'video/mpeg' => 'mp2 mpa mpe mpeg mpg mpv2',
        'audio/mpeg' => 'mp3 mpga',
        'application/vnd.ms-project' => 'mpp',
        'application/x-troff-ms' => 'ms',
        'application/oda' => 'oda',
        'application/pkcs10' => 'p10',
        'application/x-pkcs12' => 'p12 pfx',
        'application/x-pkcs7-certificates' => 'p7b spc',
        'application/x-pkcs7-mime' => 'p7c p7m',
        'application/x-pkcs7-certreqresp' => 'p7r',
        'application/x-pkcs7-signature' => 'p7s',
        'image/x-portable-bitmap' => 'pbm',
        'application/pdf' => 'pdf',
        'image/x-portable-graymap' => 'pgm',
        'application/ynd.ms-pkipko' => 'pko',
        'application/x-perfmon' => 'pma pmc pml pmr pmw',
        'image/x-png' => 'png',
        'image/x-portable-anymap' => 'pnm',
        'application/vnd.ms-powerpoint' => 'pot, pps ppt pot',
        'image/x-portable-pixmap' => 'ppm',
        'application/pics-rules' => 'prf',
        'application/x-mspublisher' => 'pub',
        'audio/x-pn-realaudio' => 'ra ram rm rmm rmvb',
        'image/x-cmu-raster' => 'ras',
        'image/x-rgb' => 'rgb',
        'application/x-troff' => 'roff t tr',
        'application/rtf' => 'rtf',
        'text/richtext' => 'rtx',
        'application/x-msschedule' => 'scd',
        'text/scriptlet' => 'sct',
        'application/set-payment-initiation' => 'setpay',
        'application/set-registration-initiation' => 'setreg',
        'application/x-sh' => 'sh',
        'application/x-shar' => 'shar',
        'application/x-stuffit' => 'sit sea',
        'application/futuresplash' => 'spl',
        'application/x-wais-source' => 'src',
        'application/vnd.ms-pkicertstore' => 'sst',
        'application/vnd.ms-pkistl' => 'stl',
        'application/x-sv4cpio' => 'sv4cpio',
        'application/x-sv4crc' => 'sv4crc',
        'application/x-tar' => 'tar taz tgz',
        'application/x-tcl' => 'tcl',
        'application/x-tex' => 'tex',
        'application/x-texinfo' => 'texi texinfo',
        'application/x-compressed' => 'tgz',
        'image/tiff' => 'tif tiff',
        'application/x-msterminal' => 'trm',
        'text/tab-separated-values' => 'tsv',
        'text/iuls' => 'uls',
        'application/x-ustar' => 'ustar',
        'text/x-vcard' => 'vcf',
        'audio/x-wav' => 'wav',
        'application/vnd.ms-works' => 'wcm wdb wks wps',
        'application/x-msmetafile' => 'wmf',
        'application/x-mswrite' => 'wri',
        'image/x-xbitmap' => 'xbm',
        'application/vnd.ms-excel' => 'xla xlc xlm xls xlt xlw',
        'image/x-xpixmap' => 'xpm',
        'image/x-xwindowdump' => 'xwd',
        'application/x-compress' => 'z',
        'application/zip' => 'zip nar',
        'application/x-zip-compressed' => 'zip',
        'application/vnd.lotus-1-2-3' => '123',
        'video/3gpp' => '3gp',
        'application/x-authoware-bin' => 'aab',
        'application/x-authoware-map' => 'aam',
        'application/x-authoware-seg' => 'aas',
        'audio/X-Alpha5' => 'als',
        'application/x-mpeg' => 'amc',
        'application/astound' => 'asd asn',
        'application/x-asap' => 'asp',
        'audio/amr-wb' => 'awb',
        'application/bld' => 'bld',
        'application/bld2' => 'bld2',
        'application/x-MS-bmp' => 'bmp',
        'application/x-bzip2' => 'bz2',
        'image/x-cals' => 'cal mil',
        'application/x-cnc' => 'ccn',
        'application/x-cocoa' => 'cco',
        'application/x-netcdf' => 'cdf nc',
        'magnus-internal/cgi' => 'cgi',
        'application/x-chat' => 'chat',
        'application/x-cmx' => 'cmx',
        'application/x-cult3d-object' => 'co',
        'application/mac-compactpro' => 'cpt',
        'chemical/x-csml' => 'csm csml',
        'x-lml/x-evm' => 'dcm evm',
        'image/x-dcx' => 'dcx',
        'application/x-dot' => 'dot',
        'drawing/x-dwf' => 'dwf',
        'application/x-autocad' => 'dwg dxf',
        'application/x-expandedbook' => 'ebk',
        'chemical/x-embl-dl-nucleotide' => 'emb embl',
        'image/x-eri' => 'eri',
        'audio/echospeech' => 'es esl',
        'application/x-earthtime' => 'etc',
        'application/x-envoy' => 'evy',
        'image/x-freehand' => 'fh4 fh5 fhc',
        'image/fif' => 'fif',
        'application/x-maker' => 'fm',
        'image/x-fpx' => 'fpx',
        'video/isivideo' => 'fvi',
        'chemical/x-gaussian-input' => 'gau',
        'application/x-gca-compressed' => 'gca',
        'x-lml/x-gdb' => 'gdb',
        'application/x-gps' => 'gps',
        'text/x-hdml' => 'hdm hdml',
        'x-conference/x-cooltalk' => 'ice',
        'image/ifs' => 'ifs',
        'audio/melody' => 'imy',
        'application/x-NET-Install' => 'ins',
        'application/x-ipscript' => 'ips',
        'application/x-ipix' => 'ipx',
        'audio/x-mod' => 'it itz m15 mdz mod s3m s3z stm ult xm xmz',
        'i-world/i-vrml' => 'ivr',
        'image/j2k' => 'j2k',
        'text/vnd.sun.j2me.app-descriptor' => 'jad',
        'application/x-jam' => 'jam',
        'application/java-archive' => 'jar',
        'application/x-java-jnlp-file' => 'jnlp',
        'application/jwc' => 'jwc',
        'application/x-kjx' => 'kjx',
        'x-lml/x-lak' => 'lak',
        'application/fastman' => 'lcc',
        'application/x-digitalloca' => 'lcl lcr',
        'application/lgh' => 'lgh',
        'x-lml/x-lml' => 'lml',
        'x-lml/x-lmlpack' => 'lmlpack',
        'application/x-lzh' => 'lzh',
        'audio/ma1' => 'ma1',
        'audio/ma2' => 'ma2',
        'audio/ma3' => 'ma3',
        'audio/ma5' => 'ma5',
        'magnus-internal/imagemap' => 'map',
        'application/mbedlet' => 'mbd',
        'application/x-mascot' => 'mct',
        'text/x-vmel' => 'mel',
        'application/x-mif' => 'mi mif',
        'audio/midi' => 'mid midi',
        'audio/x-mio' => 'mio',
        'application/x-skt-lbs' => 'mmf',
        'video/x-mng' => 'mng',
        'application/x-mocha' => 'moc mocha',
        'application/x-yumekara' => 'mof',
        'chemical/x-mdl-molfile' => 'mol',
        'chemical/x-mopac-input' => 'mop',
        'audio/x-mpeg' => 'mp2 mp3',
        'video/mp4' => 'mp4 mpg4',
        'application/vnd.mpohun.certificate' => 'mpc',
        'application/vnd.mophun.application' => 'mpn',
        'application/x-mapserver' => 'mps',
        'text/x-mrml' => 'mrl',
        'application/x-mrm' => 'mrm',
        'application/metastream' => 'mts mtx mtz mzv rtg',
        'image/nbmp' => 'nbmp',
        'x-lml/x-ndb' => 'ndb',
        'application/ndwn' => 'ndwn',
        'application/x-nif' => 'nif',
        'application/x-scream' => 'nmz',
        'image/vnd.nok-oplogo-color' => 'nokia-op-logo',
        'application/x-netfpx' => 'npx',
        'audio/nsnd' => 'nsnd',
        'application/x-neva1' => 'nva',
        'application/x-AtlasMate-Plugin' => 'oom',
        'audio/x-pac' => 'pac',
        'audio/x-epac' => 'pae',
        'application/x-pan' => 'pan',
        'image/x-pcx' => 'pcx',
        'image/x-pda' => 'pda',
        'chemical/x-pdb' => 'pdb xyz',
        'application/font-tdpfr' => 'pfr',
        'image/x-pict' => 'pict',
        'application/x-perl' => 'pm',
        'application/x-pmd' => 'pmd',
        'image/png' => 'png pnz',
        'application/x-cprplayer' => 'pqf',
        'application/cprplayer' => 'pqi',
        'application/x-prc' => 'prc',
        'application/x-ns-proxy-autoconfig' => 'proxy',
        'application/listenup' => 'ptlk',
        'video/x-pv-pvx' => 'pvx',
        'audio/vnd.qcelp' => 'qcp',
        'image/x-quicktime' => 'qti qtif',
        'text/vnd.rn-realtext3d' => 'r3t',
        'application/x-rar-compressed' => 'rar',
        'application/rdf+xml' => 'rdf',
        'image/vnd.rn-realflash' => 'rf',
        'application/x-richlink' => 'rlf',
        'audio/x-rmf' => 'rmf',
        'application/vnd.rn-realplayer' => 'rnx',
        'image/vnd.rn-realpix' => 'rp',
        'audio/x-pn-realaudio-plugin' => 'rpm',
        'text/vnd.rn-realtext' => 'rt',
        'x-lml/x-gps' => 'rte trk wpt',
        'video/vnd.rn-realvideo' => 'rv',
        'application/x-rogerwilco' => 'rwc',
        'application/x-supercard' => 'sca',
        'application/e-score' => 'sdf',
        'text/x-sgml' => 'sgm sgml',
        'magnus-internal/parsed-html' => 'shtml',
        'application/presentations' => 'shw',
        'image/si6' => 'si6',
        'image/vnd.stiwap.sis' => 'si7',
        'image/vnd.lgtwap.sis' => 'si9',
        'application/vnd.symbian.install' => 'sis',
        'application/x-Koan' => 'skd skm skp skt',
        'application/x-salsa' => 'slc',
        'audio/x-smd' => 'smd smz',
        'application/smil' => 'smi smil',
        'application/studiom' => 'smp',
        'text/x-speech' => 'spc talk',
        'application/x-sprite' => 'spr sprite',
        'application/x-spt' => 'spt',
        'application/hyperstudio' => 'stk',
        'image/vnd' => 'svf',
        'image/svg-xml' => 'svg',
        'image/svh' => 'svh',
        'x-world/x-svr' => 'svr',
        'application/x-shockwave-flash' => 'swf swfl',
        'application/x-timbuktu' => 'tbp tbt',
        'application/vnd.eri.thm' => 'thm',
        'application/x-tkined' => 'tki tkined',
        'application/toc' => 'toc',
        'image/toy' => 'toy',
        'audio/tsplayer' => 'tsi',
        'application/dsptype' => 'tsp',
        'application/t-time' => 'ttz',
        'application/x-uuencode' => 'uu uue',
        'application/x-cdlink' => 'vcd',
        'video/vdo' => 'vdo',
        'audio/vib' => 'vib',
        'video/vivo' => 'viv vivo',
        'application/vocaltec-media-desc' => 'vmd',
        'application/vocaltec-media-file' => 'vmf',
        'application/x-dreamcast-vms-info' => 'vmi',
        'application/x-dreamcast-vms' => 'vms',
        'audio/voxware' => 'vox',
        'audio/x-twinvq-plugin' => 'vqe',
        'audio/x-twinvq' => 'vqf vql',
        'x-world/x-vream' => 'vre vrw',
        'x-world/x-vrt' => 'vrt',
        'workbook/formulaone' => 'vts',
        'audio/x-ms-wax' => 'wax',
        'image/vnd.wap.wbmp' => 'wbmp',
        'application/vnd.xara' => 'web xar',
        'image/wavelet' => 'wi',
        'application/x-InstallShield' => 'wis',
        'video/x-ms-wm' => 'wm',
        'audio/x-ms-wma' => 'wma',
        'application/x-ms-wmd' => 'wmd',
        'text/vnd.wap.wml' => 'wml',
        'application/vnd.wap.wmlc' => 'wmlc',
        'text/vnd.wap.wmlscript' => 'wmls wmlscript ws',
        'application/vnd.wap.wmlscriptc' => 'wmlsc wsc',
        'audio/x-ms-wmv' => 'wmv',
        'video/x-ms-wmx' => 'wmx',
        'application/x-ms-wmz' => 'wmz',
        'image/x-up-wpng' => 'wpng',
        'video/wavelet' => 'wv',
        'video/x-ms-wvx' => 'wvx',
        'application/x-wxl' => 'wxl',
        'application/x-xdma' => 'xdm xdma',
        'application/vnd.fujixerox.docuworks' => 'xdw',
        'application/xhtml+xml' => 'xht xhtm xhtml',
        'application/x-excel' => 'xll',
        'text/xml' => 'xml xsit xsl',
        'application/x-xpinstall' => 'xpi',
        'text/xul' => 'xul',
        'application/x-yz1' => 'yz1',
        'application/x-zaurus-zac' => 'zac',
    );
}

//所有user_agent
function useragent(){
    return array (
        'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:16.0) Gecko/20121026 Firefox/16.0',
        'Mozilla/5.0 (Linux; U; Android 2.2.1; zh-cn; HTC_Wildfire_A3333 Build/FRG83D) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
        'Mozilla/5.0 (Windows NT 5.2) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.122 Safari/534.30',
        'Opera/9.80 (Windows NT 5.1; U; zh-cn) Presto/2.9.168 Version/11.50',
        'Mozilla/5.0 (iPad; U; CPU OS 4_3_3 like Mac OS X; zh-cn) AppleWebKit/533.17.9 (KHTML, like Gecko) Mobile/8J2',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.84 Safari/535.11 LBBROWSER',
        'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; XBLWP7; ZuneWP7)',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)',
        'UCWEB7.0.2.37/28/999',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)',
        'Mozilla/5.0 (Windows NT 5.2) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.122 Safari/534.30',
        'Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3_2 like Mac OS X; zh-cn) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5',
        'Mozilla/5.0 (Linux; U; Android 2.3.7; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
        'MQQBrowser/26 Mozilla/5.0 (Linux; U; Android 2.3.7; zh-cn; MB200 Build/GRJ22; CyanogenMod-7) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
        'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; SV1; QQDownload 732; .NET4.0C; .NET4.0E; 360SE)',
        'Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1',
        'Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A5313e Safari/7534.48.3',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A5313e Safari/7534.48.3',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727; TheWorld)',
        'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)',
        'Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0',
        'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.133 Safari/534.16',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.71 Safari/537.1 LBBROWSER',
        'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; SV1; QQDownload 732; .NET4.0C; .NET4.0E; SE 2.X MetaSr 1.0)',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A5313e Safari/7534.48.3',
        'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1',
        'Mozilla/5.0 (Windows; U; Windows NT 5.1; ) AppleWebKit/534.12 (KHTML, like Gecko) Maxthon/3.0 Safari/534.12',
        'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.84 Safari/535.11 SE 2.X MetaSr 1.0',
        'Mozilla/4.0 (compatible; MSIE 6.0; ) Opera/UCWEB7.0.2.37/28/999',
        'Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; zh-cn) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5',
        'Openwave/ UCWEB7.0.2.37/28/999',
        'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.2; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET4.0E; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C)',
        'Opera/9.80 (Android 2.3.4; Linux; Opera Mobi/build-1107180945; U; en-GB) Presto/2.8.149 Version/11.10',
        'Mozilla/5.0 (iPad; U; CPU OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)',
        'Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5',
        'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN; rv:1.9.2.15) Gecko/20110303 Firefox/3.6.15',
        'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.202 Safari/535.1',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; QQBrowser/7.0.3698.400)',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; LBBROWSER)',
        'Mozilla/5.0 (Linux; U; Android 3.0; en-us; Xoom Build/HRI39) AppleWebKit/534.13 (KHTML, like Gecko) Version/4.0 Safari/534.13',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; QQDownload 732; .NET4.0C; .NET4.0E; LBBROWSER)"',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
        'Mozilla/5.0 (Linux; U; Android 2.3.3; zh-cn; HTC_DesireS_S510e Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.202 Safari/535.1',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)',
        'Mozilla/5.0 (iPad; U; CPU OS 4_2_1 like Mac OS X; zh-cn) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8C148 Safari/6533.18.5',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; QQDownload 732; .NET4.0C; .NET4.0E)',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; QQDownload 732; .NET4.0C; .NET4.0E)',
        'MQQBrowser/25 (Linux; U; 2.3.3; zh-cn; HTC Desire S Build/GRI40;480*800)',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; SAMSUNG; OMNIA7)',
        'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET4.0E; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C)',
        'Mozilla/5.0 (hp-tablet; Linux; hpwOS/3.0.0; U; en-US) AppleWebKit/534.6 (KHTML, like Gecko) wOSBrowser/233.70 Safari/534.6 TouchPad/1.0',
        'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:2.0b13pre) Gecko/20110307 Firefox/4.0b13pre',
        'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; QQDownload 732; .NET4.0C; .NET4.0E)',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)',
        'Mozilla/5.0 (SymbianOS/9.3; U; Series60/3.2 NokiaE75-1 /110.48.125 Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.11 TaoBrowser/2.0 Safari/536.11',
        'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:16.0) Gecko/20100101 Firefox/16.0',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; HTC; Titan)',
        'NOKIA5700/ UCWEB7.0.2.37/28/999',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2) AppleWebKit/534.51.22 (KHTML, like Gecko) Version/5.1.1 Safari/534.51.22',
        'Mozilla/5.0 (BlackBerry; U; BlackBerry 9800; en) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.337 Mobile Safari/534.1+',
        'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)',
        'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaN97-1/20.0.019; Profile/MIDP-2.1 Configuration/CLDC-1.1) AppleWebKit/525 (KHTML, like Gecko) BrowserNG/7.1.18124',
        'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET4.0E; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C)',
        'Mozilla/5.0 (X11; U; Linux x86_64; zh-CN; rv:1.9.2.10) Gecko/20100922 Ubuntu/10.10 (maverick) Firefox/3.6.10',
        'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)',
    );
}